### ISSUE TITLE
introspection?

### ISSUE THREAD

**Issue by dkoerner** [ospray/OSPRay#117]
Hi,
I wonder if it is also possible to query the state of the ospray API somehow. Currently I understand that the API only supports setting information such as parameter values etc. There could be use cases where it would be benefitial to have query functions which allow to query parameter values, object types or even things such as the list of supported parameternames on an ospray object. Having such functions could keep a software architecture built around ospray more slim and elegant. 

What are your thoughts on that?

Best,
David
P.S.: feel free to close the issue after commenting....

**Comment by carsonbrownlee** [comment]
hi David, 
Thanks for the input!  Unfortunately, OSPRay does not currently let you query parameter values, mainly because this complicates the MPI device we are currently working on.  We definitely all agree that this would be beneficial and make debugging state significantly easier.  We have discussed a scenegraph type structure for all object params but no eta on this yet.

**Comment by jeffamstutz** [comment]
Hi David,

We used to have functions to query parameter values for objects currently in memory, but these functions are only trivial to implement when rendering locally.

Moving forward, we currently implement 2 devices: LocalDevice and MPIDevice (and deprecated a third -> KNC COIDevice). The local device implements the API to do all rendering locally on the CPU, which is what you get by default when you initilaize OSPRay. However, other devices are able to map slightly different semantics to the same API calls currently defined. Our current MPI device allows a single application to treat an entire cluster as a giant "offload" device, where objects are not local to the memory space of the application. This was similar to our COI device which would do the same, but doing so with (potentially multiple) KNC cards, where objects are also not local to the CPU the app is running on.

It was possible for us to implement the parameter query functions in these contexts, but it had very negative impact on performance as cross-node synchronization is expensive; thus we removed them completely. Furthermore, this issue is even more problematic (and perhaps not even possible to correctly implement) in a distributed application, where each node may make _different_ API calls. Thus for apps which rely upon OSPRay tracking their data, almost the entirety of OSPRay internal objects would have to be queryable to allow apps to "discover" what the scene looks like on one particular node. Ultimately, we decided to keep the API in its current form to minimize divergence in how apps use the API when using different device rendering backends. In it's current form, the entire API can be called identically between local, MPI, [and COI] devices, where a single app can render locally or across cluster nodes without even needing to recompile.

The solution we settled on is directing responsibility of tracking parameter values to the layer of client code which is making OSPRay API calls. IMHO, it actually makes more sense to keep such information in the app as OSPRay doesn't care about what the scene _means_ to the app, rather that there's just geometry and/or volumetric data to be rendered "by something". Depending on the complexity of your application, this could be fairly simple to implement or very big/comprehensive. As Carson suggested, a scene graph on top of OSPRay is a great way to solve the problem. We do have one in our samples apps (https://github.com/ospray/OSPRay/tree/devel/apps/common/sg), but we can't commit to maintaining/extending it as we do the core API at this time.

I hope that helps!

Cheers,
Jeff

**Comment by dkoerner** [comment]
I haven't thought about the implication of state queries in the context of distributed rendering. Thank you guys for elaborating on this. Having a SG on top of ospray on the client code side seems the way to go then.

Best,
David

**Comment by johguenther** [comment]
While I agree to all above (i.e. OSPRay's API staying write-only) I like to discuss the other (orthogonal) aspect of the original question: How about exposing query functions to get a list of the offered parameters of an object and their meta information, i.e. not the value, but information such as type, default value, minimum and maximum valid value? This can be quite a useful feature, also allowing applications to easily make use of  (unknown) modules / plug-ins based on the SDK.

**Comment by carsonbrownlee** [comment]
johannes,
absolutely.  We have discussed this previously as part of a scenegraph and you're right it would be very useful to users to have a check for missing required fields for instance and a state graph that we can verify rather than just throwing exceptions by hand.  Just not sure where that is on our priority list right now.
