### ISSUE TITLE
Access Embree device in user geometry module

### ISSUE THREAD

**Issue by timbiedert** [ospray/OSPRay#120]
Is it possible to access the Embree device used by OSPRay within a user geometry module?

The API does provide `OSPDevice ospGetCurrentDevice();` and in ospray::api::Device, there is `static RTCDevice embreeDevice`.

**Comment by jeffamstutz** [comment]
Ah, you are confusing an OSPRay device with an Embree device. ```ospGetCurrentDevice()``` gets a handle to the object which implements the ```ospray.h``` API functions. I assume that is not what you are looking for.

The Embree device is, as you found, defined as a static member in ```ospray::api::Device```. The Embree device used to exist as global variable, which our MPI workers depended upon being able to extern a reference to it. Once our MPI workers use a concept of a Device to implement themselves, I want to make the Embree device a non-static member.

Thus for now, you can access the static member directly anywhere in the code by including ```Device.h```. In the future (probably ```v1.3.0``` at the earliest), know that this will eventually become a non-static member that will require getting a pointer/reference to the current device in order to access.

Hope that helps!

Jeff

**Comment by timbiedert** [comment]
Hi Jeff, thanks for the reply.  Actually, I am not confusing them :-)   The question was rather:  How to access the Embree device given the OSPRay device.

I also thought that I could just include Device.h to access the static field. However, after installing OSPRay, Device.h is not available (on my system: anywhere in /usr/local/include/ospray/).

**Comment by jeffamstutz** [comment]
Sorry about the confusion, you've uncovered a bug in our SDK install...```Device.h``` should be there! :)

Fixed now in ```devel```, which will be a part of our next release.

**Comment by timbiedert** [comment]
Great, thanks!

Another approach independent from OSPRay:  The Embree scene handle is already accessible within (OSPRay) user geometry. Is there some way in Embree to query a scene for the device it was created on?  

Best,
Tim

**Comment by ingowald** [comment]
Just to elaborate:

- Device.h _should_ be there; it's a bug that it isn't, and Jeff will fix.

- once it _is_ installed in the SDK path, the current way of accessing 
the embree device is the static Device member.

Cheers,

Ingo

**Comment by ingowald** [comment]
No, not through the API. That's why we pass it along with the device.

Same goes for "scene handle from geometry ID" - embree doesn't expose 
this back-translation, so ospray geometries (have to) track the model 
they are in.

Cheers,

Ingo

**Comment by timbiedert** [comment]
Works now, thank you!
