### ISSUE TITLE
building "KNL" mode actually builds multi-target "sse2,avx515"

### ISSUE THREAD

**Issue by ingowald** [ospray/ospray#124]
Here's the compile-line that cmake generates
cd /home/wald/Projects/ospray/bin/ospray && /home/wald/Projects/ispc-v1.9.1-linux/ispc -I /home/wald/Projects/ospray/ospray -I /home/wald/Projects/ospray/ospray/include -I /home/wald/Projects/ospray/ospray -I /home/wald/Projects/ospray -I /home/wald/Projects/ospray/bin -I /home/wald/opt/lib/cmake/embree-2.13.0/../../../include --arch=x86-64 --addressing=32 -O3 --target=avx512knl-i32x16,sse2 --woff --opt=fast-math --pic --opt=disable-assertions -h /home/wald/Projects/ospray/bin/ospray/GhostBlockBrickedVolume_ispc.h -MMM /home/wald/Projects/ospray/bin/ospray/local_volume/GhostBlockBrickedVolume.dev.idep -o /home/wald/Projects/ospray/bin/ospray/local_volume/GhostBlockBrickedVolume.dev.o /home/wald/Projects/ospray/ospray/volume/GhostBlockBrickedVolume.ispc

**Comment by johguenther** [comment]
Yes, this is intentional (a workaround, see also [`ispc.cmake` line 150ff](https://github.com/ospray/ospray/blob/master/components/ospcommon/cmake/ispc.cmake#L150-L156)): Unfortunately ISPC only generates the ISA suffixes of symbols when more than one target is compiled. And without the ISA suffixes there will be problems when linking to Embree.
