### ISSUE TITLE
Quad Light wrong and antialias in pathtracer

### ISSUE THREAD

**Issue by loppirob** [ospray/ospray#127]
I'm 'trying to implement Ospray in our software ArredoCAD via the API but I found the following problems:
The quad light also illuminate behind not only in the half space
The quad light are seen in reflections even if hidden
Antialiasing is not working properly 

OSPRAY API in ArredoCAD:
![accumulatedframe](https://cloud.githubusercontent.com/assets/24694093/23297359/88e6476a-fa79-11e6-85b3-bf2fc5e3cbc0.jpg)

Quad light correct:
![quad_correct](https://cloud.githubusercontent.com/assets/24694093/23297357/88e4ed16-fa79-11e6-9269-c55cc40313f9.jpg)

Quad light wrong OSPRAY:
![quad_wrong](https://cloud.githubusercontent.com/assets/24694093/23297358/88e53e7e-fa79-11e6-84fe-4c4305e27df3.jpg)

Quad light hidden correct in the mirrors :
![quad_hidden_correct_in_mirror](https://cloud.githubusercontent.com/assets/24694093/23297360/88e6ffca-fa79-11e6-98cf-6b64705bf74a.jpg)

Quad light hidden wrong in the mirrors OSPRAY:
![quad_hidden_wrong_in_mirror](https://cloud.githubusercontent.com/assets/24694093/23297361/88e724dc-fa79-11e6-8a73-529e4b21de1f.jpg)

**Comment by johguenther** [comment]
Hi,
I'm happy to read that you consider to integrate OSPRay :-)

Which version of OSPRay are you using? I assume v1.2.0? One problem with light sources was fixed in 081587e6438a6d88f8e1e788680978093e687091, which will be part of a next patch release soon. Chances are high that this fixes your problem shown in the 3rd image (quad light illuminating also behind).

The behavior that the "invisible" light can be seen in the mirror is actually correct regarding the current definition: according to the documentation the parameter `isVisible` controls “whether the light can be *directly* seen”, i.e. via the camera, but not indirectly in reflections. The difficulty lies in a consistent definition of the “visibility” behavior. If you want the light to be also invisible when seen indirectly, this actually means that the light is not illuminating anymore.
What we could do is to introduce a new parameter `isVisibleInReflections` with the meaning whether the light is visible via *ideal specular* reflections. Thus, when turned off, it won't be seen in the mirror anymore (changing your last image). However, please note that when you change the material of the mirror to be slightly rough (e.g. a highly polished metal) to get highly glossy reflections the light will immediately be visible again (because the reflection is then not ideal specular anymore). Would that be acceptable for you?

With anti-aliasing problems I guess you mean high (>>1) contrast edges (like the borders of a visible quad light with intensity 20, or the left lamp arm, which is in front of a high intensity background). This is actually an artifact introduced when clipping high dynamic range (HDR) images to the low dynamic range of the display. One solution is to have a better tone mapping algorithm which properly handles anti-aliasing. Another often used workround (which is also supported by OSPRay) is to clip contributions before accumulating. You can do this by setting the path tracer parameter `maxContribution` to e.g. 5 or 10 (depending on you scene brightness and tone mapping operator). A downside of this workaround is that bright highlights (e.g. on the chrome stair handles in the right of your first image) might loose brilliance.

Best regards,
  Johannes

**Comment by loppirob** [comment]
Dear Mr Günter,

thank you for your answer,

I have used the version 1.2 (the latest) and we are waiting for the new precompiled binary version with the right quadlights. We hope that it will come soon because we would like to participate to a fair Euroluce at the beginning of April in Milan with OSPray and it is important to solve the problem because our customers use invisible quadlights  a lot (to light up just some areas of the scene).

If it is possibile and feasible, I think that isVisibleInReflections is ok for solving the problem with the hidden quadlights in the reflections.

As to antialias problem, you told me that it was possible to use maxContribution to e.g. 5 or 10, I used the value 5 and you can see in the example I sent you, that there are no fireflies (white dots that otherwise would have appeare). By the way we are quite satisfied with the all scene anti-aliasing.

I thank you in advance for your attention

Best regards


Roberto


Dinamica srl

Hi,
I'm happy to read that you consider to integrate OSPRay :-)

Which version of OSPRay are you using? I assume v1.2.0? One problem with light sources was fixed in 081587e<https://github.com/ospray/ospray/commit/081587e6438a6d88f8e1e788680978093e687091>, which will be part of a next patch release soon. Chances are high that this fixes your problem shown in the 3rd image (quad light illuminating also behind).

The behavior that the "invisible" light can be seen in the mirror is actually correct regarding the current definition: according to the documentation the parameter isVisible controls “whether the light can be directly seen”, i.e. via the camera, but not indirectly in reflections. The difficulty lies in a consistent definition of the “visibility” behavior. If you want the light to be also invisible when seen indirectly, this actually means that the light is not illuminating anymore.
What we could do is to introduce a new parameter isVisibleInReflections with the meaning whether the light is visible via ideal specular reflections. Thus, when turned off, it won't be seen in the mirror anymore (changing your last image). However, please note that when you change the material of the mirror to be slightly rough (e.g. a highly polished metal) to get highly glossy reflections the light will immediately be visible again (because the reflection is then not ideal specular anymore). Would that be acceptable for you?

With anti-aliasing problems I guess you mean high (>>1) contrast edges (like the borders of a visible quad light with intensity 20, or the left lamp arm, which is in front of a high intensity background). This is actually an artifact introduced when clipping high dynamic range (HDR) images to the low dynamic range of the display. One solution is to have a better tone mapping algorithm which properly handles anti-aliasing. Another often used workround (which is also supported by OSPRay) is to clip contributions before accumulating. You can do this by setting the path tracer parameter maxContribution to e.g. 5 or 10 (depending on you scene brightness and tone mapping operator). A downside of this workaround is that bright highlights (e.g. on the chrome stair handles in the right of your first image) might loose brilliance.

Best regards,
Johannes

**Comment by johguenther** [comment]
Hello Roberto,
version 1.2.1 of OSPRay will be released before April. However, it won't contain a potential `isVisibleInReflections` feature, which will come in v1.3.0 the earliest (which will be later than April). Nevertheless, you could also easily (we hope) compile OSPRay yourself to get interesting changes independent of our binary releases (or to see whether the mentioned fix really solves your quad light problem). See [Building OSPRay from Source](http://www.ospray.org/getting_ospray.html#building-ospray-from-source).

Best regards,
  Johannes

**Comment by loppirob** [comment]
Dear Mr Günter,

thank you for your answer,
waiting for the new version, i did more tests and I found another anomaly: when the "distant light" has a greater than 42 degrees angle of incidence is filtered completely from glass material. Since we use glass in the windows when the distant light exceeds the inclination of 42 degrees the room is completely dark and the sun light effect disappear.

For the glass material we use these values:

glass
attenuationColor = 1, 1, 1
attenuationDistance = 1
eta = 1.45

you can 'fix it?
Or is there a workaround?


I sent 4 images that contain a cylinder and a sheet of glass vertically with the "distant light" set to 42,43 and 44 degrees of tilt in the vertical and in the horizontal 0.
as you can 'see with 42 degrees above the direct light it is completely blocked and the result is a shadow on the floor.


Best regards,
Roberto

www.dinamicasoft.com<http://www.dinamicasoft.com>

**Comment by johguenther** [comment]
The Glass material implements refraction realistically and thus requires closed geometry – it is meant for thick objects. Windows are usually only modeled with one surface, so you probably see [total internal reflection](https://en.wikipedia.org/wiki/Total_internal_reflection) (which happens at ~43° for eta=1.45).
For windows you may want to use the (undocumented, because work-in-progress) ThinGlass material. Its color can be currently controlled by a `transmission` parameter.

**Comment by johguenther** [comment]
[Release 1.2.1](https://github.com/ospray/OSPRay/releases/v1.2.1) is now available, please test whether it indeed fixes your quad light problem.

If you like to be notified of future releases you can subscribe to the [OSPRay announce](https://groups.google.com/forum/#!forum/ospray-announce/join) mailing list.

**Comment by loppirob** [comment]
Dear Mr Günter,

We tested the new version of Ospray 1.2.1 and the quadlight problem has been fixed, that's very good.
Unfortunately, however, we have found a certain slowness in the rendering process (after two days of calculation the scene
 is still not completed while with the old engine Embree-renderer-2.3.2
it becomes clean and sharp in a few hours, obviously using the same parameters)

How could  we speed up the calculation time?

The old Embree renderer is compiled with RELEASEAVX option and uses the latest version of EMBREE.DLL.
For Ospray we are using the DLL pre compiled contained in directory ospray-1.2.1.windows\bin

We currently use the following parameters to speed up the rendering time Ospray without loosing too much quality:

ospSet1f (renderer, "minContribution", 0.2);
ospSet1f (renderer, "maxContribution", 5.0);

ospSet1i (renderer, "spp", 1);
ospSet1i (renderer, "maxDepth", 10);

We've also tried varianceThreshold using various values: the calculation time is shorter but the quality of the scene has not improved (noisy effect)

                ospSet1f(renderer, "varianceThreshold", variance);
                framebuffer = ospNewFrameBuffer(imgSize, OSP_FB_SRGBA, OSP_FB_COLOR | OSP_FB_ACCUM  | OSP_FB_VARIANCE);


The module used in ArredoCAD to use the API OSPRAY han been compiled with Visual studio 2010 for platform 64bit.

We've tried to compile the Ospray library, installed Cmake 3.8 64bit, TBB (https://www.threadingbuildingblocks.org/), intel SPMD Program Compiler (esiste solo a 32bit)

We have added the environmental vatiables like embree_DIR = directory embree 2.14 x64

        But an Error appears: only 64bit architecture supported

Is it possible to compile Ospray so that it uses AVX? Or has it been already compiled to use at most the fastest speed of the processor?

We can't understand, why Ospray works so slow compared to embree-renderer, also in small scenes (empty room with a window and just ambient light or HDRI with a white image rgb 1,1,1).


I attach also an example of an image obtained after 3 days of processing (with pixeled effect) using a PC with Intel i7 Processor.

Could you please help me with this matter?


Thank you very much for your attention


best regards

 Sincerely, Roberto

Dinamica s.r.l.

**Comment by johguenther** [comment]
OSPRay and Embree use AVX2 (and higher) per default (when the CPU supports it) and also with the release packages.

I guess the error "only 64bit architecture supported" comes from CMake? When configuring the first time with CMake (or after deleting its cache) you need to select a 64bit Generator, e.g. "Visual Studio 10 2010 **Win64**".

Could you attache the image? It is missing. Three days seem really to much; a high quality image (FullHD, no perceivable noise) should typically be ready in one, two hours on an i7.

**Comment by loppirob** [comment]
Dear Mr Günter,

you can see the images created directly from ArredoCAD and rendered by OSPRAY in this link (our working in progress):

https://service.dinamicasoft.com/arredocad360/euroluce.php

D-RAY3 preview is rendered by OSPRAY api
D-RAY2 is rendered by embree renderer



Or download from:

    https://1drv.ms/f/s!Am1TMzE6ruDptx78-fXVUl-y4_oV

here i put also the scene file and the source code in CPP that read the scene file exported by ArredoCAD and call OSPRAY API.

What appen when the CPU don't supports AVX2? (our case may be)
I hope that OSPRAY switch automaticaly to AVX

The 360 images are 4096 x1024  resolution, very big but the problem is the same with 1920x1080 images (not 360)

I attached the image, i dont know why you cant receive ...

from dos shell:

cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang ..

    the error is:  only 64bit architecture supported

from cmake version 3.7.2
If you cant open the attached image, i paste here the message  (we have selected "Visual Studio 10 2010 Win64"):

CMake Error at CMakeLists.txt:59 (INCLUDE_DIRECTORIES_ISPC):
  Unknown CMake command "INCLUDE_DIRECTORIES_ISPC".


But if the OSPRAY api and precompiled DLL use the best possible speed of the PC we dont need to recompile, or not?


best regards

 Sincerely, Roberto

Dinamica s.r.l.



Il 17/03/2017 17:10, Johannes Günther ha scritto:

OSPRay and Embree use AVX2 (and higher) per default (when the CPU supports it) and also with the release packages.

I guess the error "only 64bit architecture supported" comes from CMake? When configuring the first time with CMake (or after deleting its cache) you need to select a 64bit Generator, e.g. "Visual Studio 10 2010 Win64".

Could you attache the image? It is missing. Three days seem really to much; a high quality image (FullHD, no perceivable noise) should typically be ready in one, two hours on an i7.

**Comment by johguenther** [comment]
Please be aware that our conversation is still on your GitHub issue ticket #127, are your download links really intended for the public (you can edit / remove these messages directly at GitHub #127)? We can also continue the discussion internally, you can reach me via "johannes dot guenther at intel dot com".

Yes, if the CPU does not support AVX2 OSPRay automatically falls back to AVX or SSE4 (the CPU must support at least SSE4.1 to run OSPRay).

You only need to compile OSPRay yourself if you like to test new features in the `devel` branch that are not released yet, or if you want to disabled features you do not need (e.g. to get smaller DLLs). Otherwise the precompiled packages we provide for each release should be perfectly fine.

On Windows using the CMake-GUI is probably the easiest way, there you can select the Generator in a drop-down menu. On the command line you need to specify it via the `-G` flag (also refer to [scripts/release/win.bat](https://github.com/ospray/ospray/blob/master/scripts/release/win.bat#L28)), e.g.
```
cmake -G "Visual Studio 10 2010 Win64" -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang ..
```
Also, you need to start with the top-level folder of OSPRay for cmake to avoid the "INCLUDE_DIRECTORIES_ISPC not found" error.


I will have a closer look regarding the performance issues soon.
