### ISSUE TITLE
issue in loading objs using sg::importOBJ

### ISSUE THREAD

**Issue by swatinair123** [ospray/ospray#155]
Hi,

1.I am trying to load an obj file using sg::importOBJ  in ospExampleViewerSG
The code is as below.
auto world_ptr= sg::createNode(fn.name(), "World");
sg::importOBJ(world_ptr, fn.name());
where fn.name is the obj file path.
But the obj files are not getting loaded . 
2. I am trying to load around 5 obj files. the files are loading using ospExampleViewerSG. But all the 5 objs are merged.

Please kindly advise.

**Comment by jeffamstutz** [comment]
Hello,

Our scene graph uses different "traversal" types to operate on scene data. Our importer nodes will not do anything until a "commit" traversal is done. Let's say you have a renderer node called ```renderer_ptr``` and your world called ```world_ptr``` as mentioned above. You would add and commit the world to the renderer with:

```c++
auto renderer_ptr = sg::createNode("renderer", "Renderer");
renderer_ptr->add(world_ptr);
renderer_ptr->traverse("commit");
```

That will cause the importer node (contained in ```world_ptr```) to do the work of opening the objfile and loading the scene, as well as committing all the relevant OSPRay objects.

Currently ospExampleViewerSG will create one importer node per input file and put them all in the same scene. I am actively working on an "timestep" node type which will handle switching between contained geometries for the sake of animation. This will fix the woody doll demo on the website. I'm shooting to have it in our upcoming ```v1.4.0``` release.

In the meantime, you could have multiple renderers each contain the individual time steps, or have one renderer that has its world swapped out when rendering multiple time steps. However, this will likely not perform well because without a node which can easily switch between geometries, the entire scene (materials, geometries, etc.) may end up getting unnecessarily recommitted for each time step. 

Alternatively you could work with the raw OSPRay API and implement these things yourself, but that is a much larger task to undertake.

Cheers,
Jeff

**Comment by swatinair123** [comment]
Thanks a lot Jeff.

**Comment by carsonbrownlee** [comment]
Note that before you can remove individual instances in the scenegraph by setting "enabled" to false.
I have created a "Selector" node that selects a single child node for rendering, which can also be acted upon by an "Animator" node.  I have submitted this as a merge request on devel.  You can run the animated woody doll on the demos page by this command:
./ospExampleViewer /bertha/graphics_scenes/crytek-sponza/sponza.obj --scale 300 300 300 --translate 250 -11 0 --animation /bertha/wooddoll/wooddoll*.obj -aoSamples=8 --plane -step=0.03 -vp 667.492554 186.974228 76.008301 -vu 0.000000 1.000000 0.000000 -vi 84.557503 188.199417 -38.148270 -aoSamples=0 -ambient:intensity=.85 -sun:intensity=3 -sun:direction="-.3 -1 -.04"

**Comment by johguenther** [comment]
Please (re-)open if there are further questions.
