### ISSUE TITLE
details on producing precompiled binaries

### ISSUE THREAD

**Issue by matthewberger** [ospray/ospray#174]
Hi -

Regarding the binaries that are provided under the Downloads section, I was wondering if additional details could be provided on how these were compiled. I am interested in compiling a (slightly modified) version of OSPRay and using an installed version (produced via make install) on a different platform. Unfortunately, make install produces an executable and libraries that result in gcc version errors on said platform when running the binaries, whereas the precompiled binaries do not. So I'd like to understand the differences between running make install to produce the binaries (with all compilation options set to default), and how the precompiled binaries were produced.

Thanks!

**Comment by jeffamstutz** [comment]
Howdy,

What OS/compiler are you building with? And what are you try to then deploy/run to? This shouldn't be to bad to debug.

If you build with a non-standard compiler on an old OS, or build on one OS and run on another, it's easy to get tripped up with incompatibility of libstdc++ (C++ standard library) link dependencies. This is why we build the pre-built binaries on the oldest libstdc++ we can: it makes the binaries as widely compatible as possible. That means for us, we build them with icc and gcc-4.8.2's standard library on CentOS6. However, if you can avoid CentOS6 (and old versions of SLES), please do. :)

FWIW, all of our release steps are visible in ```scripts/release/linux.sh```, which gets invoked by a gitlab CI job, which can be found in ```.gitlab-ci.yml``` in the root directory. We do use internal environment modules to bring in icc, gcc, and cmake, but all that does is point the environment to the compilers/tools of interest (i.e. appending PATH and LD_LIBRARY_PATH environment variables).

Building with pretty much any compiler will give you mostly the same performance for OSPRay, because most of our performance-sensitive code is compiled by ispc, so don't get too confused by us using icc. :)

Cheers,
Jeff

**Comment by jeffamstutz** [comment]
Also, just to be complete: you can extend/modify OSPRay from the binaries. We install all the internal headers in the ```include/ospray/SDK``` directory, allowing applications to extend OSPRay from an install. It isn't (yet) well advertised, but that could be an alternative way to extent OSPRay for your needs.

Of course it's all free and open-source, so it's completely up to you are comfortable with. :)

**Comment by johguenther** [comment]
Please reopen if you have further questions.
