### ISSUE TITLE
Is possible improve the performance by a clip window?

### ISSUE THREAD

**Issue by cshan** [ospray/ospray#177]
![image](https://user-images.githubusercontent.com/1759640/30543920-5234cecc-9cb7-11e7-9aa5-972d588c7e8a.png)
Hi, 
My question is I have a object but it just a small area in the screen, I only need render the green area is ok, but the full framebuffer is large, it will take me a lot of CPU resource to rendering full view(most is black). does ospray have any way to improve the performance by this use case?

Thanks,
Chengliang

**Comment by wilsonCernWq** [comment]
The imageStart and imageEnd options in camera can change the rendering region to any region we want. I feel that's exactly what you want :)

**Comment by johguenther** [comment]
`imageStart/End` can indeed be used to restrict rendering to e.g. the green area, however, the complete framebuffer will be filled. So, you would need to create a new, smaller framebuffer and later manually copy its content into the blue framebuffer.

Alternatively, if you actually accumulate many frames for the final rendering you can also try using the `varianceThreshold` renderer parameter together with a `OSP_FB_VARIANCE` framebuffer, then OSPray will automatically not compute the black (marked blue) regions, because its variance should be zero. See also the [documentation](http://www.ospray.org/documentation.html), Sections Renderer and Rendering

**Comment by johguenther** [comment]
Please reopen if you have further questions.
