### ISSUE TITLE
Seg fault when framebuffer size > (2^31)/4 pixels

### ISSUE THREAD

**Issue by jediati** [ospray/ospray#195]
So an image of size 23,170 x 23,170 ( = 536,848,900 < 536,870,912 = 2^31 / 4) renders just fine
the same scene at size 23,171 x 21,171 ( = 536,895,241 > 536,870,912 = 2^31 / 4) has a segmentation fault in ospRenderFrame() call. it successfully makes and clears the framebuffer first. I'm using SRGBA, which is where i think the factor of 4 comes in re integer overflow:

printf("about to make framebuffer\n"); 
OSPFrameBuffer framebuffer = ospNewFrameBuffer((osp::vec2i&)img_size,
         OSP_FB_SRGBA, OSP_FB_COLOR); 
ospFrameBufferClear(framebuffer, OSP_FB_COLOR);
printf("Made framebuffer\n");
// Finally, render the image and save it out
ospRenderFrame(framebuffer, renderer, OSP_FB_COLOR);
printf("done render\n");

**Comment by johguenther** [comment]
I agree that it looks like a problem with an index overflowing (in particular because we use 32bit addressing in ispc generated code). Until the fix you can try the following workarounds:
- split the final image into "smaller" segments (below the 23170 size) and adjust the camera parameters `imageStart`/`imageEnd` accordingly to stitch the segments seamlessly together afterwards (all provided it would just be a handful of segments).
- try MPI-based rendering (even locally on one machine), which will use the Distributed Framebuffer

**Comment by ingowald** [comment]
Mpi probably won't fix this, since the final image is reassembled at the master with the same class that does the local framebuffer...

**Comment by johguenther** [comment]
I successfully rendered 44k×33k images (sRGB and HDR float): OSPRay can now generate GigaPixel images :-).

Be aware that you need tons of memory for the accumulation buffer, etc (64GB is barely enough); and most tools cannot handle images that large...
