### ISSUE TITLE
Return from blocking MPI offload worker

### ISSUE THREAD

**Issue by tbiedert** [ospray/ospray#200]
Hi,

I manually create an MPI offloading device using `OSPDevice device = ospNewDevice("mpi_offload");`, and the subsequent `ospDeviceCommit(device);` call blocks on all ranks > 0 as expected.

After I have finished my rendering, how can I signal on rank 0 that OSPRay should terminate, i.e., return from that blocking function on all worker ranks? I just want to perform a proper shutdown on all ranks after rendering.

Thanks!

**Comment by jeffamstutz** [comment]
Hi Tim,

We currently have an issue on shutdown inside of OSPRay with the ```mpi_offload``` device. The intended use case is to have OSPRay call ```std::terminate(0)``` instead of the application needing to worry about shutdown: thus it is intentional that we will never return from either ```ospInit()``` or ```ospDeviceCommit()``` in this case. Any crashes on shutdown are on our end and we are investigating them!

If you _want_ control back in the application, it sounds like this is a different use case than we currently handle. The ```mpi_offload``` device is truely intended for non-distributed applications --> there are a couple of options:

1) Use different MPI communicators for the application MPI workers vs. the OSPRay MPI workers. The ```devel``` branch (will be in ```v1.5.0```), we added the ability to give the device a premade MPI communicator for OSPRay to use instead of OSPRay creating one.

@Twinklebear any input here wrt MPI communicator setups?

2) Do all cleanup prior to your rendering phase. Given that all worker ranks will not have any data associated with them given to OSPRay (everything goes through rank 0 with the offload device), everything could be cleaned up (i.e. memory) before you initialize OSPRay. This only works, however, if you do a "1 shot" of pre-processing then rendering. Once you are rendering, you'd be stuck there until you are done.

3) Use the distributed device. The semantics of the ```mpi_distributed``` device are expecting that the application is, in-fact, distributed. There are some drawbacks here, however: we only have a raycast renderer implemented and it is currently more intended for data distributed rendering (which is not what you are doing).

Regardless, we could be open to the idea of adding features to the distributed device that would enable multiple "modes" of rendering (replicated vs. distributed data): though that could get complicated pretty quickly.

I suppose option 1 would fit better for what you are doing, option 2 would be more of a "hack" if it fits your setup's assumptions/needs, and option 3 would be much more forward looking for more creative uses of the OSPRay API.

Hopefully that helps clarify things!

Cheers,
Jeff

**Comment by Twinklebear** [comment]
For option 1, you'd still need to use the `mpi_distributed` device for this, so would be limited to the basic scivis raycaster written there. The comm partitioning stuff is mostly targeted for in situ applications where you'd have an MPI-parallel simulation w/ one rank per-core running OSPRay with one rank per-node, so each rank is still specifying different data for distributed rendering.

I'm not sure if it'd be good to change the finalize work unit on the workers to not directly call `std::exit` but instead return back out of the OSPRay API call. Currently the workers just get and execute work units, but don't get any feedback back from them in the "receive work unit" loop. Adding this would make the client code have to be aware of the MPI parallel nature of the application, as now you'll have to handle the case that the workers are returning out from this call when you quit.

Along the lines of 2, if might be possible to register an `atexit` callback to do your cleanup, since that should be called when we exit with `std::exit`.

**Comment by jeffamstutz** [comment]
I think we will officially close this, but for those still interested we now ship the MPI module in a [separate repo](https://github.com/ospray/module_mpi).

**Comment by Twinklebear** [comment]
Note that this will still happen in the offload device, but for this use case I recommend using the distributed device (which can now also do image-parallel data-replicated rendering)
