### ISSUE TITLE
Serialize model

### ISSUE THREAD

**Issue by tbiedert** [ospray/ospray#214]
Is it possible to easily serialize the complete model, e.g., to disk, and deserialze it in a different session/app?

I assume something like that is already implemented in the MPI offloading device. Would be cool to have an API to it, such as "serialize model to binary buffer" or similar.

Thanks!

**Comment by jeffamstutz** [comment]
I think this is something we want to support in ```ospray_sg``` (our scene graph) fairly soon. Disk IO is beyond the scope of the OSPRay API, but it is certainly something a scene graph could easily support.

The plan is to soon start delivering ```ospray_sg``` in OSPRay installs so you can choose to not re-invent that wheel if you don't need/want to. We have some API stabilizing to do with it, but I hope we can get that done and "delivered" sooner rather than later: there are a number of features more appropriate for a scene graph that users ask for occasionally, so clearly there's a non-trivial demand for it.

**Comment by tbiedert** [comment]
Cool, thanks!  I don't need disk IO per se.  A general "serialize to/deserialize from byte buffer" solution would be sufficient.
