### ISSUE TITLE
Link ospray module libraries to application

### ISSUE THREAD

**Issue by wilsonCernWq** [ospray/ospray#222]
Hi All

I had a question about linking ospray module libraries to applications.

As we know `osprayConfig.cmake` only provides ospray core libraries like `libospray.so`. And when users want to load a module, ospray will try to search `libospray_module_<name>.so` and link it. It means the installed ospray library directory should added in the system search path, e.g. `LD_LIBRARY_PATH`, or being compiled using `-L`(for gcc)/`link_libraries`(for cmake) 

Modern cmake somehow doesn't recommend people to use `link_libraries`, which is probably the reason why ospray doesn't provide an variable to the installed library directory e.g. `<install_dir>/lib64`. However I think this is not very desirable when ospray is being integrated into large applications like VisIt. I mean if we consider the application as a self-contained software, it should not modify any environmental variables after launching it. Using relative paths allows application to install ospray directly into its build directory without worrying about repackaging. Without that, we will need to do many hacks for simply fixing the library search paths.

Therefore I want to have the cmake variable, say `OSPRAY_LIBRARY_PATH` back pointing to the installed `lib` directory. Or allowing `osprayConfig.cmake` to handle component arguments if I missed important reasons for not using the `link_libraries` call. 

By handling component arguments I mean, for example if we want to have `OSPRAY_LIBRARIES ` variable containing `libospray_module_mpi.so` and `libospray_module_visit.so`, we should be able to call directly
```cmake
find_package(ospray REQUIRED COMPONENTS mpi visit)
``` 
and have the required libraries added into the cmake variable. Then application can link the libraries using absolute paths.

Will this be a good feature for ospray?

Qi

**Comment by jeffamstutz** [comment]
Hi Qi,

You're definitely on the right track here. The CMake ```link_libraries()``` comand should definitely be avoided. The current solution is for users to place modules on their ```LD_LIBRARY_PATH```, but I definitely see the advantages to having another option.

What you've called out with having a ```COMPONENTS``` section in the OSPRay ```find_package()``` config is something I thought of a long time ago, but never took the time to research how to do, let alone implement it. I think that idea is sound: other major packages, such as Qt5, follow this convention. Ideally, any and all modules would be visible as optionally fetchable components.

Where the idea diverges with our plans a bit is that the current ```osprayConfig.cmake``` exports a list of _libraries_, not CMake _targets_. Modern CMake package configs should actually export targets, where all library/include/flag dependencies get resolved completely in a single ```taget_link_libraries()``` command in the client CMake. Figuring out how to make a target-based CMake package config work with components would require some research, but is apparently doable (e.g. Qt5 is doing it).

So in the end: yes, we would welcome the idea of exposing particular OSPRay components in an install. FWIW, if you end up directly linking against a component (say, the MPI module), then you don't actually have to call ```ospLoadModule()``` anymore because the symbols would be linked to the final binary. That would leave ```ospLoadModule()``` for extending an existing OSPRay install with modules not built concurrently with the source tree that generated that install (though that could have its own issues, at the moment).

Is there a particular setup you'd like to enable? Perhaps we can find some sort of middle-ground before the revamp of OSPRay's CMake package config to use targets is done.

**Comment by wilsonCernWq** [comment]
Hi Jeff

Currently I am using the variables `LIBRARY_PATH_PREFIX` and `LIBRARY_SUFFIX` to manually link module libraries. Those variables are temporary variables in `osprayConfig.cmake' and "luckily" they are not cleaned :D

I think it will be better, as a middle-ground" solution to officially allow users to use those variables? For example make it `OSPRAY_LIBRARY_PATH_PREFIX` and `OSPRAY_LIBRARY_SUFFIX` ?

Best

Qi

**Comment by jeffamstutz** [comment]
This should be solved by linking against the module target exported by CMake. Please let us know if linking a module directly has any unforeseen issues.
