### ISSUE TITLE
Black Streamlines

### ISSUE THREAD

**Issue by tomvierjahn** [ospray/ospray#223]
Doing some tests towards using streamlines, I cannot get colours to work. They remain black.
Maybe you can point me at what I am missing? 

MWE: https://github.com/tomvierjahn/ospray_streamline_tests

My System:
* Mac OS X 10.13.3
* apple-clang / Apple LLVM version 9.0.0
* ISPC 1.9.2 (via homebrew)
* Embree 2.17.2 (built from source)
* OSPRay 1.4.3 (built from source)

**Comment by jeffamstutz** [comment]
Hi,

I had a look at the test repo you created, thanks for doing that! I noticed a couple of things:

- ```SetupLight()``` does indeed create a light from the renderer, but the renderer expects an ```OSPData``` of ```OSPLight``` handles. Have a look at ```ospTutorial.cpp``` for an example, but basically you can just add the following lines after ```ambient_light.commit()```:
```C++
  auto lightHandle = ambient_light.handle();
  ospray::cpp::Data lights(1, OSP_LIGHT, &lightHandle);
  lights.commit();
  renderer_->set("lights", lights);
```
- You call ```SetupLight()``` after ```SetupRenderer()```, so even if you had the above fix for ```SetupLight()```, it wouldn't get committed before the frame gets rendered. Thus the issue actually wasn't colors, rather only that there wasn't any light shining on the geometry...FWIW, I sanity checked this first by seeing what the ```ao``` renderer generated (it ignores all lights and just uses hard-coded AO).

Hopefully that helps, let me know if anything is still unclear!

Cheers,
Jeff

**Comment by tomvierjahn** [comment]
Hi Jeff,

thanks a lot.

It is amazing how quickly one forgets stuff ... Thanks for reminding me of the light data to be set … and that its in fact the AO renderer that does need no lights … ;-)

By the way, the way to add and set lights feels a bit counter-intuitive: Lights are the only (?) entities that are created via a factory. Since it is done that way, I have expected the renderer to already know about the light. May I ask you to briefly fill me in why it is done this way?

Cheers,
Tom

**Comment by jeffamstutz** [comment]
The issue with how lights are handled is somewhat related to materials: both currently require an instance of a renderer _not_ because the actual instance is required, rather we use the _type_ of renderer to figure out internally what kind of light/material needs to be created. Thus an "ambient" light means different things between the path tracer and the scivis renderer (in theory), same with materials such as the "obj" material. Futhermore, we would then need a way to remove lights added implicitly: the current method of using an OSPData array means that you can keep control of what lights are currently in the scene by manipulating arrays of light handles.

I think a clearer API function would look something like:

```C++
// declaration in ospray.h
OSPMaterial ospNewLight(const char *renderer_type, const char *light_type);

// usage
auto light = ospNewLight("scivis", "ambient");
```
Thus right now, you could technically make 2 different instances of the scivis renderer and use lights created from one in the other.

In the future we would like to figure out a way to divorce the renderer requirement for creating lights and materials, and instead have a master list of light/material types which renderers construct lazily when a frame gets rendered. However, that will likely come with or after OSPRay v2.0 because it's such a fundamental change.

In the mean time, we could probably deprecate (or just keep two versions?) the current function and instead point users to the above version instead. Would that make sense to you?

**Comment by tomvierjahn** [comment]
`auto light = ospNewLight("scivis", "ambient");` is so much clearer in how and in which order to use it.

Coming back to my MWE, I could then first call `SetupLight()` (just setting the lights' parameters) and then `SetupRenderer()` (configuring the renderer and assigning the lights) – just ordered naturally.

**Comment by tomvierjahn** [comment]
Thanks a lot for sharing the details, Jeff!

**Comment by jeffamstutz** [comment]
Yup, glad that makes sense to you and thanks for the feedback! I'll propose it next week to the team in our weekly meeting, but I think it's likely that we will make the API change.

**Comment by jeffamstutz** [comment]
The team agreed that the proposed API change makes sense, so we will implement it as a part of the upcoming ```v1.5.0``` release. We will, however, keep the old version of the function for backwards compatibility and mark its declaration as deprecated.
