### ISSUE TITLE
volume dimensions not updating

### ISSUE THREAD

**Issue by carsonbrownlee** [ospray/ospray#23]
calls to ospsetregion and dimensions do not seem to have an affect, likely due to the check in blockbricked for ispccode=NULL only updating the ispc code once.

**Comment by ospray-owner** [comment]
Hi Carson,

Prior to the first call to ospSetRegion(), the volume dimensions and voxel type must be set. When ospSetRegion() is called the first time, the underlying volume is created and the dimensions / voxel type can no longer be changed.

We are making an API change for v0.9, where the dimensions and voxel type will be arguments to ospNewVolume() rather than parameters. Hopefully that will make this behavior more clear.

Thanks!
Greg
