### ISSUE TITLE
Readd a module example

### ISSUE THREAD

**Issue by sz-1011101** [ospray/ospray#257]
Release 1.6 does not seem to have a simple module example for custom geometries such as pluggableGeometryExample in earlier versions.

**Comment by jeffamstutz** [comment]
We've re-added this as a part of ```devel```, which will become ```v1.7.0``` in the future. We temporarily removed the module when we ported to Embree 3 because we ran out of time (we had the rare occasion that a release had a specific date requirement). Until we have it in an official release, however, we'll leave this issue open.

**Comment by sz-1011101** [comment]
Thanks!
