### ISSUE TITLE
Constant colored material with scivis renderer?

### ISSUE THREAD

**Issue by paulmelis** [ospray/ospray#320]
Is there a way, with the scivis renderer, to get constant surface shading, i.e. one that disregards the surface normal and lights? The OBJ Material provides control over diffuse and specular components, but does not have an ambient term (I would normally set diffuse and specular contributions to black to get pure ambient).

**Comment by samcaulfield** [comment]
Rendering the OSP_FB_ALBEDO channel in the frame buffer produces an image that technically has constant lighting contribution of 0 because all illumination sources are ignored.

Then you could either:
- Add the ambient lighting contribution to the albedo map by post-processing. I'm sure there's a better way of doing this than post-processing but I thought I'd mention it anyway.
- Set the diffuse color parameter of the object's material to the ambient lighting term you want because the renderer might still respect the upper limit on reflectivity from that when rendering the albedo map. I'm not sure if this will work though but I think I encountered this behaviour before.

**Comment by johguenther** [comment]
Wow, creative suggestion to use the albedo frambuffer channel , didn't think about that one :-)

One other way may be to use just one ambient light, and set `aoSamples` to zero (i.e., disabling shadow), which results in ambient illumination (on the diffuse color).

**Comment by carsonbrownlee** [comment]
Johannes suggestion is the expected route to achieve ambient only lighting, making sure to remove any other other lights.

**Comment by paulmelis** [comment]
> One other way may be to use just one ambient light, and set aoSamples to zero (i.e., disabling shadow), which results in ambient illumination (on the diffuse color).

Okay, thanks, that indeed does what I wanted. By the way, "disabling shadow" put me on the wrong foot, as there is the separate `shadowsEnabled` flag, but that has nothing to do with AO in ospray, right?

PS I usually also forget that one can do tricks in image space apart as alternative to going for the pure rendering-based solution :wink:

**Comment by carsonbrownlee** [comment]
AO and shadows are indeed different.  There should be no shadows with only an ambient light, however; so that shouldn't actually do anything. While the image buffer approach is valid, it would incur overhead over just rendering pure ambient lighting as computing unnecessary lighting would be additional compute as well as the albedo buffer.

**Comment by johguenther** [comment]
Yes, just to confirm: in SciVis renderer, shadowing (from point and directional lights) is controlled via `shadowsEnabled`. Ambient intensity is inferred from the ambient light, and the quality of Ambient Occlusion is controlled via `aoSamples`. Using zero AO samples disables AO shadowing, but ambient illumination is still in effect.
