### ISSUE TITLE
Slice plane behaviour

### ISSUE THREAD

**Issue by paulmelis** [ospray/ospray#321]
While debugging some other weird slice plane behaviour I'm trying to figure out the image below made by the attached test case.

![slices](https://user-images.githubusercontent.com/1408287/57409511-c603cd00-71e8-11e9-84ca-56441d062330.png)

This is with a 16^3 uchar volume with all values equal to 100. The TF is red at 0 and green at 255. How come the plane isn't a single color, as presumably all samples have the same value?

[code.zip](https://github.com/ospray/ospray/files/3159364/code.zip)

**Comment by jeffamstutz** [comment]
Hi,

In the code you posed, it looks like you never set the `voxelData` parameter on the volume, so the volume is likely sampling garbage values. When I added prior to the volume commit:

```c++
ospSetObject(volume, "voxelData", voxels);
```

I get an all green slice.

Hope that helps!

Cheers,
Jeff

**Comment by jeffamstutz** [comment]
Also, the value range needs to be set on the transfer function to align the tf with the volume:

```c++
ospSet2f(tf, "valueRange", 0, 255);
```

**Comment by paulmelis** [comment]
Ouch, sorry for the noise :-( Also, my original "weird slice plane behaviour" was caused by mistakenly setting the plane equation through an `OSPData` of 4 x OSP_FLOAT instead of 1x OSP_FLOAT4.

Is there some method in ospray to catch stupid errors like this (e.g. enable assertions and/or extra checks)?

**Comment by johguenther** [comment]
Good point: we have checks here and there, but apparently do not cover all parameters of all objects. So, we need to improve this...

**Comment by jeffamstutz** [comment]
Don't worry about it, we are here to help however we can! To be honest, these kinds of bugs are my favorite to fix because they don't require making a patch release! ;)

Seriously though, sometimes it can be too easy to make a mistake and our story of validating objects on commit isn't exactly consistent (just as @johguenther said). On that note, there are 2 things we'd like to do:

1. **Better status/error messages in object commits**: basically, if we _can_ easily detect that something is wrong, then we should at least try to tell you as much as we can. Obviously that can only go so far, but even then we could enable certain expensive checks when `--osp:debug` is enabled (or something like that). These kinds of improvements will likely be ongoing.
2. **Scenegraph rewrite**: the `ospray_sg` library is a better place to put validation of objects as it manages all the scene data/params that it hands to the underlying OSPRay API. This library has been very useful for development in v1.x, but we would like to make it easier for users to use...this includes things like documentation, examples, and code cleanups. Also, given that it is a C++ library (unlike OSPRay being a pure-C API), we can do richer things to ensure correctness and be more "expressive" with intent in its API design. We will be looking to finish up the last bit of v2.0 API changes before getting back to `ospray_sg`, but I really want our team to commit to the scene graph being a complete product of its own.
