### ISSUE TITLE
How to run 'ospTutorial' in Xcode?

### ISSUE THREAD

**Issue by fdvty** [ospray/ospray#329]
Hello,

I'm trying to start ospTutorial in Xcode

I have added 'libospray.1.8.5.dylib' into the linking list, but it always said library not found for     -lospray.1.8.5 . Should I add something else? 

I'm completely new to OSPRay, so just tell me if you need further information.

Thank you!

**Comment by BruceCherniak** [comment]
Hello,

I have not tried with Xcode, but the ``libembree.dylib`` libraries must also be found.  Have you built your own embree or installed via brew or some other method?

**Comment by fdvty** [comment]
No. I directly downloaded the precompiled package from OSPRay's website.

**Comment by jeffamstutz** [comment]
Hi,

I know nothing about how XCode works, but ospTutorial is a standalone (example) application. Most IDEs run applications that are found to be built in the project being worked on, not example apps pre-built by a package. Thus to run ospTutorial within an IDE, you should be compiling OSPRay itself and probably not the pre-built binaries from the website.

That said, if you are generating an XCode project with CMake, then you can `find_package(ospray)` and use it as a library in an application you are writing (which you can find documented at the bottom of our [downloads page](http://www.ospray.org/downloads.html)).

Otherwise the things you find in the `bin/` directory within the binary packages (or from a manual install you create) are intended simply to be executed from the command line. Getting them working in a particular IDE is outside our expertise: there may be a way to setup your `PATH` and `DYLD_LIBRARY_PATH` inside XCode to point to `bin` and `lib` in the pre-built packages respectively, but that doesn't sound like a typical use of an IDE.

Just to be clear, OSPRay is only a C/C++ library. All the executables found in our packages are merely examples/demonstrations of using the OSPRay library, not the end-product to be consumed for something else.

Hope this helps!

Cheers,
Jeff
