### ISSUE TITLE
Undersampling? (i.e. samplesperpixel < 0)

### ISSUE THREAD

**Issue by AndrewJDR** [ospray/ospray#346]
Thanks for the project!

Do ospray's pathtracer and scivis backends support undersampling, that is: sampling at some rate less than one per pixel, such as once per every 4 pixels? This can be useful for faster rendering at times of user camera interaction.

I do see a usage of a negative spp value in OSPApp.cpp, which is promising:
```
renderer["spp"] = -1;
```

However, at least in the scenegraph codepath within `sg/Renderer.cpp`, I see a minmax being set on the spp of `1, 128`:
```
child("spp").setMinMax(1,128);
```

So I'm not sure a negative spp has any actual effect (And this is also confirmed by trying it). I do note that this can be done by rendering to a smaller framebuffer size and upscaling, but it'd be handy not to have to manage that on the usage-code side.

Overall, would also be great to have an up-to-date listing of setting/value pairs for getting the absolute best render times possible for fast interactions, with a separate list relevant to the pathtracer and scivis renderer.
The `if (fast) {` block within OSPApp.app looks promising. However, it doesn't include any potentially relevant pathtracer-only related settings (`rouletteDepth` / `maxContribution`) and it also may have out-of-date information (e.g. the -1 for `spp` that is probably ultimately clamped by minmax, mentioned above).

**Comment by jeffamstutz** [comment]
Hi,

We ended up removing negative spp values from the base OSPRay API (in `v1.7.0`) due to issues with accumulation, especially in distributed rendering cases. Thus you are correct in observing that this should be done by having two different frame buffers at different resolutions. This keeps things easier for renderer implementers to maintain correctness of accumulation across frames.

If you have a look at example viewer, the scene graph does implement the concept of an "interaction resolution" and "resolution", which you can find in the `app` menu.

**Comment by johguenther** [comment]
We didn't notice OpenSWR limiting interactivity when using GL upscaling. And even a huge 10ms time for that would still be fast enough. As alternative to GL one can also use other libraries to upscale the framebuffer, for example there is [IPP image transforms](https://software.intel.com/en-us/ipp-dev-reference-image-geometry-transforms).

Including upscaling directly in OSPRay is not so easy. Although we have image operations (post processing nodes), those cannot change the resolution. Adding this flexibility complicates OSPRay's implementation and also its usage considerably. Thus I think it is fine to leave that as external task.
