### ISSUE TITLE
Use Shoemake's arcball for qtViewer

### ISSUE THREAD

**Issue by ghost** [ospray/ospray#37]
The current control is extremely unpredictable and difficult to use. Classic arcball would resolve this issue.

**Comment by johguenther** [comment]
Hi,
I had a look at [Shoemake's paper](https://www.talisman.org/~erlkonig/misc/shoemake92-arcball.pdf) (had not known it before) &ndash; very interesting indeed.
However, please don't expect an implementation soon; because the viewer applications are &#8220;just&#8221; for demonstration purposes, development of core OSPRay has priority.

Best regards,
  Johannes

**Comment by pavolzetor** [comment]
It is the best arcball, because you can do full 360 rotation with one mouse drag. It is quite simple to implement (I have started, possibly will do pull request), but I haven't added panning yet.

This is a simple example of just rotation:
https://github.com/pavolzetor/tommy
