### ISSUE TITLE
How to compile the ospTutorial files

### ISSUE THREAD

**Issue by FFFwarp** [ospray/ospray#408]
i'm new to rendering areas, i want to build this example.
but when i run this command, there's an error. could you tell me how can i compile this file?

 gcc -std=c99 ospTutorial/ospTutorial.c -I include -L . -lospray -Wl,-rpath,. -o ospTutorial

/usr/bin/ld: cannot open output file ospTutorial: Is a directory
collect2: error: ld returned 1 exit status

Thanks a lot!!!!!!

**Comment by johguenther** [comment]
It looks like you are in the `apps` directory: when the linker tries to create the file `ospTutorial` it cannot, because `ospTutorial` already exists (and it is a directory). The command line you use is from v1.8, better use the current v2.0 with the current command line
```sh
gcc -std=c99 ../apps/ospTutorial/ospTutorial.c -I ../ospray/include -L . -lospray -Wl,-rpath,. -o ospTutorial
```
(given paths assume you are in a build directory under the OSPRay root folder, and that OSPRay has already been compiled (which should also automatically compile the tutorial))

**Comment by johguenther** [comment]
Please reopen id the problem still persists.
