### ISSUE TITLE
Templated ospSetParam documentation

### ISSUE THREAD

**Issue by pauljurczak** [ospray/ospray#414]
Change log for v2.0.0 reads: "Type-specific parameter setting functions have been consolidated into a single ospSetParam API call". I don't see templated `ospSetParam` in documentation at https://www.ospray.org/documentation.html#parameters

**Comment by paulmelis** [comment]
I think that's because the API docs describe the C API, while the templated version is (obviously) only present in the C++ wrapper.

**Comment by pauljurczak** [comment]
Is C++ wrapper documented somewhere?

**Comment by paulmelis** [comment]
Don’t think so, but the C++ examples plus ospray_cpp headers should give information. The API names aren’t that different.

**Comment by johguenther** [comment]
The documentation link https://www.ospray.org/documentation.html#parameters points exactly to the C99 version of the single `ospSetParam` function: instead of a template argument that function takes an `OSPDataType` parameter plus the (void) pointer to the variable. (up to v1.8 we had a zoo of set param functions, one for each type, like `ospSetFloat`, `ospSetVec3i`, ...)
