### ISSUE TITLE
Iso surfaces broken

### ISSUE THREAD

**Issue by StasJ** [ospray/ospray#444]
The surface is missed. This is not fixed by increasing the sampling rate and it exists in both regular and unstructured grids.

![iso](https://user-images.githubusercontent.com/2772687/86855516-b8113c80-c077-11ea-8cef-f7600762aa2b.png)

**Comment by Twinklebear** [comment]
Hey @StasJ , is there a scaling factor being applied to the volume here through the instance transform (or grid spacing?). Could you try disabling AO and see if that resolves the artifact? (setting `aoSamples` 0 on the renderer).

**Comment by StasJ** [comment]
Hi @Twinklebear, there is no scaling factor however disabling AO does resolve the artifact.

**Comment by Twinklebear** [comment]
Oh cool, that's good to hear then since this is likely also an issue we've got fixed in the coming release. The latest release of OpenVKL added support for returning an epsilon value (i.e., for shadow rays) from the hit iterator which we now use in the renderer to adjust the AO ray interval and avoid these artifacts. This should be fixed if you use the latest OpenVKL release and OSPRay devel, and when the next OSPRay release is out

**Comment by StasJ** [comment]
Sounds good, thanks!

**Comment by johguenther** [comment]
I'll close since the fix is in v2.2.0; please reopen if there are still artifacts.
