### ISSUE TITLE
Non-uniform affine scaling results in incorrect normals

### ISSUE THREAD

**Issue by StasJ** [ospray/ospray#446]
Original isosurface:

![1x](https://user-images.githubusercontent.com/2772687/87111704-3c55f200-c227-11ea-9e59-e6dbdf10b889.png)

The same isosurface after its Z coordinates are scaled by 1/100 and then scaled 100x by an affine transform:

![100x](https://user-images.githubusercontent.com/2772687/87111805-7f17ca00-c227-11ea-9630-dae18a66e4b2.png)

**Comment by Twinklebear** [comment]
Hi @StasJ , just to clarify: Are you applying this non-uniform scaling through a transform on the instance of through the grid spacing parameter?

**Comment by StasJ** [comment]
Hi @Twinklebear, I am applying the non-uniform scaling through a transform.

**Comment by StasJ** [comment]
The issue is fixed however it appears to have introduced regressions in the isosurface lighting as a whole. 

Rendered with 2.2.0:

![2 2 0](https://user-images.githubusercontent.com/2772687/94065193-08ab5280-fda8-11ea-8450-b15b4f3a1ef2.png)

Rendered with devel:

![devel](https://user-images.githubusercontent.com/2772687/94065203-0e089d00-fda8-11ea-8f73-b571a0455f10.png)

**Comment by johguenther** [comment]
The changed lighting is likely independent of the isosurface and rather due to the renderer changes introduced in v2.3.0: SciVis now again uses all light sources and again evaluates specular material properties. If you like the previous lighting better, then you can use the  new `ao` renderer (a rename of the v2.2 scivis).

**Comment by johguenther** [comment]
Also fixes #344.
