### ISSUE TITLE
API error handling is always bound to active device

### ISSUE THREAD

**Issue by target-san** [ospray/ospray#455]
Hello,

All C API calls implementations use bracket macros `OSPRAY_CATCH_BEGIN`, `OSPRAY_CATCH_END`. Both ones working with devices and other managed objects. `OSPRAY_CATCH_END` uses `handleError` function internally which is used to turn exceptions into error codes. What looks strange to me is that `handleError` always retrieves current device as viable target for error context, both when we have no device selected or we're operating not on device which is currently active.

Would it be possible to replace device-specific error handling with thread-local static variables and route existing `ospDeviceGetLastError*` calls to them? This would allow to both report errors happening before device is activated and remove inconsistency of error info stored in device which didn't cause it?

Thanks

**Comment by jeffamstutz** [comment]
The OSPRay API is designed around a single current device, so the only place an error can originate from is the current device or a few corner cases when initializing OSPRay with a device for the first time. Even devices can be updated with new parameter values and commits after they are set to being active, so the current setup ensures no leaked exceptions through the API (because it's C99) and maximally utilizes the status/error callbacks set on the active device when an error is encountered to minimize unwanted stdout/stderr traffic.

We have no support for more than one active device in parallel, especially between multiple application threads. Such requirements are planned for OSPRay v3.0 as they inject the need for major, incompatible API changes.

**Comment by target-san** [comment]
> Even devices can be updated with new parameter values and commits after they are set to being active

I would argue that I didn't find any kind of `this == currentDevice()` checks. Though I understand I might've missed them, such errors like "operated device is not active" would also land in active device's error context. Even if you have such constraints as described above on your API, context-less access to error status makes things so much easier, especially when one writes bindings to other languages.

**Comment by johguenther** [comment]
For v3 we plan to remove the implicit, global `currentDevice` and make that explicit in the API. BTW: on which language bindings are you working on?

**Comment by target-san** [comment]
It's .NET, implemented in C++/CLI.
