### ISSUE TITLE
Question: possible to clip volumes but not geometry?

### ISSUE THREAD

**Issue by timsandstrom** [ospray/ospray#467]
Seems that "clippingGeometry" applies to the entire embree scene... i.e. everything in the world...? 
is there a way to isolate the clip to a specific instance/group/volume? 

I tried having vols and triangles each in a separate instance/group with only the vol group having a "clippingGeometery" param 
but that still clipped the tris...

PerlinNoiseVolumes::buildWorld() demonstrates clipping, but clips both vol and geometry 
[if you make the radius of the clip sphere 1.5, the ground plane will be clipped as well - as of ospray-2.4.0]

---

**Comment by johguenther** [comment]
Right now clipping is global, affecting all geometry and volumes in the World. Limiting clipping to sub-trees or specific objects would be a new feature.

A workaround could be to render two images: 1. only geometry without clipping, 2. only volumes with clipping plus using the depth-buffer from 1. as `map_maxDepth` to have correct occlusion when compositing both images.

Another alternative could be to have a more complex clipping geometry to limit the clipping to the volume bounds, e.g. instead of a clipping plane using the union of the volume bounding box and the plane (a sliced box) .

**Comment by timsandstrom** [comment]
Indeed, thanks for the prompt response!
