### ISSUE TITLE
Transparent geometry support

### ISSUE THREAD

**Issue by florianlink** [ospray/OSPRay#50]
I did some tests with transparent meshes and it was unclear to me, which of the different renderer supports transparent meshes. I have transparency in the vertex colors of my meshes, which I pass as "vertex.color" using FLOAT4. None of the renderers seems to use that alpha.
I tested adding a OSPMaterial and added a "d" value of 0.5. This causes the mesh to get transparent in OBJ renderer, but not in the rest of the renderers (AO/SciVis/VolumeRayCaster).

Did I miss something or is this just not implemented?

**Comment by jeffamstutz** [comment]
Each renderer has its own view on handling material and geometric properties, one of which being transparency. The OBJ renderer (depricated, will eventually be removed) does support transparency, but it is known that the AO and VolumeRayCaster renderers do not support it. The AO renderer will not support transparency in favor of simplicity: it is intentionally a small renderer to support a very short shading phase and for demonstration of how to implement a renderer. Surface rendering support in the VolumeRayCaster was added a while ago because we did not yet have a renderer which did both volumes and surfaces together, where the focus was rendering opaque geometry inside of a volume (a common situation in visualization applications).

The new SciVis renderer will support transparency, which could be viewed as either a "bug" or "not yet implemented feature". We will call out that feature explicitly in release notes when it is implemented.

Also, FWIW, we are always open to merge requests. :)

**Comment by florianlink** [comment]
Ok, I am looking forward to this SciVis feature! I think it would also make
a lot of sense in the VolumeRayCaster. At least we often want to show
transparent meshes in a volume, currently we use Depthpeeling and a
multipass Glsl ray caster in OpenGL. Would be great if this was also
supported on the CPU.

**Comment by florianlink** [comment]
I updated to 0.10 today and tried it by setting "d" on the material to 0.2 for my meshes.
The first hit surface gets rendered (with correct alpha applied), but I don't see any geometry shining through / behind it.
(Using scivis renderer, "triangles" geometry, with shadows on/off).

Are there any other parameters/options I need to enable first?

**Comment by timbiedert** [comment]
Currently in the SciVis renderer:

- No material:  info.d = dg.color.w;   
- With material: info.d = mat->d * get1f(mat->map_d, dg.st, 1.f);

Do you intentionally ignore the color.w when using materials?

In my scenario I have a triangle mesh with varying alpha values per vertex.  This works fine without material, but with a material (in order to have proper Phong shading) there is only a constant opacity for the whole mesh.
