### ISSUE TITLE
Conda-Forge support

### ISSUE THREAD

**Issue by StasJ** [ospray/ospray#517]
We are adding support for distributing Vapor ([NCAR/VAPOR](https://github.com/NCAR/VAPOR)) using Conda. We would like to include OSPRay with that build however it doesn't appear that OSPRay has a Conda package. Are there any plans to add Conda support?

**Comment by johguenther** [comment]
As of now: no plans for Conda. It seems that there is no Conda generator in CMake/CPack.

**Comment by eunos-1128** [comment]
I am currently working on creating a Conda package for OSPRay on conda-forge so that OSPRay can be used from other Conda packages that require it, which is necessary for me.

Once conda-packaging OSPRay’s dependencies, ispc, rkcommon, openvkl, and OpenImageDenoise, are complete, I plan to begin work on conda-packageing OSPRay.
(ispc has already been done)

**Comment by eunos-1128** [comment]
I have submitted [the build recipe](https://github.com/conda-forge/staged-recipes/pull/33242#issuecomment-4410897201) to conda-forge.

Once this PR is merged, we will be able to install OSPray using `conda install -c conda-forge ospray`, which will support Linux, macOS, and Windows.

I designed it so that build variants supporting MPI are also built simultaneously for users who wish to use MPI with OSPray.

hello, @johguenther 
Would you be willing to become one of the maintainers with me for the conda-forge recipe?
(You may occasionally receive notifications on GitHub for automated updates on conda-forge)

There wouldn’t be any specific work for you to do, but I may ask you questions via issues when problems arise.
(On conda-forge, maintainers are provided with a package management repository called "feedstock" for each conda package.)

**Comment by eunos-1128** [comment]
We can now install OSPRay v3.2.0 using `conda install -c conda-forge ospray`.

Pre-compiled packages are available for installation on Windows (x86_64), macOS (x86_64, arm64), and Linux (x86_64, arm64).

https://anaconda.org/channels/conda-forge/packages/ospray/overview
