### ISSUE TITLE
TransferFunction colour space

### ISSUE THREAD

**Issue by Fingolfin1196** [ospray/ospray#533]
Due to my dissatisfaction with ParaView, I have implemented a simple volume renderer using OSPRay to visualize the results of some simulations I have run. While most aspects now work as intended, I have not been able to recreate the default transfer function of ParaView, which consists of the colours `#3b4cc0`, `#dddddd`, and `#b40426` in HTML notation, using OSPRay. I have interpolated these colours in sRGB to generate 256 colours, converted those to linear RGB, and used that to set the `color` property of the `TransferFunction` that I use in my `VolumetricModel`. The results are rendered to a framebuffer using the `OSP_FB_SRGBA` format and stored directly to a `PNG` file using OpenImageIO (the results are equivalent to the PPM helper from OSPRay). However, using the `scivis` renderer and appropriate opacity values, I get the following result:
![scivis](https://user-images.githubusercontent.com/16902662/179542025-8764e519-9a2d-4ff9-b0b5-95c55425cff0.png)
This is in contrast to ParaView using its OSPRay backend (only the strip at the centre is correct, the outer parts exhibit some interpolation issues that are not relevant for this issue):
![ParaView](https://user-images.githubusercontent.com/16902662/179542353-28758f24-ee3e-49fa-bb97-fbc05029fdaa.png)
Since the colours are off significantly and I have not been able to identify the actual colour space in which the transfer function colours need to be specified, I see no solution other than a custom lookup table to find the values that OSPRay requires to output the correct colours, which is obviously a bad approach. I would be very glad about some help resolving this issue.

**Comment by Fingolfin1196** [comment]
Dropping the conversion does not solve the issue. If I use `OSP_FB_SRGBA` as the format of the framebuffer, the gamma is obviously wrong (in addition to the hues being wrong):
![accumulated-mix](https://user-images.githubusercontent.com/16902662/179574964-1867fdbd-8549-4a67-a15c-e05f4c24f165.png)
If I use `OSP_FB_RGBA8` (i.e. I pretend to use linear RGB everywhere), I get a similar result as before:
![accumulated-linear](https://user-images.githubusercontent.com/16902662/179574984-812564f0-ff7a-4821-b986-7d2e8b51c8b9.png)

**Comment by demarle** [comment]
How are you interpolating between those three (Red, White and Blue) values? ParaView's default interpolation mode is "diverging".  If your interpolation is different, it could explain the differences you are seeing between your and ParaView+OSPRay's colors.

See https://vtk.org/doc/nightly/html/classvtkColorTransferFunction.html#a7308a34ac7b702136fe9298946b720db and https://gitlab.kitware.com/vtk/vtk/-/blob/master/Rendering/Core/vtkColorTransferFunction.cxx#L155 for the implementation. In VTK2OSPRay the interpolation should always be close to VTK's GL backend because we populate OSPRay's LUT with whatever VTK's TF gives us (https://gitlab.kitware.com/vtk/vtk/-/blob/master/Rendering/RayTracing/vtkOSPRayVolumeMapperNode.cxx#L399).

**Comment by Fingolfin1196** [comment]
The interpolation was indeed the difference: When using RGB interpolation in ParaView, I get a very similar result to the original OSPRay image, and if I use diverging interpolation for the transfer function in OSPRay, I get the expected output:
![accumulated](https://user-images.githubusercontent.com/16902662/179932541-ce08220d-3032-497d-aaf0-ed0f8c014706.png)
Thank you very much for pointing out the interpolation and providing the relevant links to VTK that helped me implement the diverging interpolation in my code. My issue is resolved.
