### ISSUE TITLE
Custom material support

### ISSUE THREAD

**Issue by NadirRoGue** [ospray/ospray#551]
Hello,

I am trying to implement custom materials for OSPRay, however, I noticed that SciVis renderer does not use the getBSDF or getTransparency functions of the Material interface, but rather just casts the material to OBJ and then uses its member variables.

This would mean that a custom material would be ignored on this renderer. Is there any approach I might have ignored to implement a custom material, or is there any plans in the future to support this?

For context, I want to create a material that uses abs(dot(view, normal)) as an alpha parameter to interpolate between full white opaque and full transparent to have a "ghost" shading on transparent surfaces, which will allow to highlight the edges.

Kind regards.

**Comment by chegarty3** [comment]
I know this doesn't solve the issue for you, but most of the materials found in the official documentation (https://www.ospray.org/documentation.html#materials) are only supported by the PathTracer renderer.  In fact, looking at the documentation, the OBJ material may be the only material that SciVis supports (which would be consistent with casting the material to OBJ).

Rather than a custom material, you may be able to implement a custom, procedural Texture and use it in the opacity channel of the OBJ material using "map_d".

**Comment by NadirRoGue** [comment]
Thank you! Thats actually a pretty good solution!

**Comment by NadirRoGue** [comment]
@chegarty3 Thanks for the suggestion, however there is a limiting factor and is that the texture functions do not receive ray information (which I need to implement the shading type that I need).

**Comment by johguenther** [comment]
Indeed, currently custom materials (i.e., anything else than OBJ) only works in the path tracer, which is unfortunate and we like to change that "some day".

What you like to achieve may be easier done patching the SciVis (and pathtracer) renderer directly.

**Comment by NadirRoGue** [comment]
Thanks for the heads up!
