### ISSUE TITLE
ospray 2.12.0 build embree missing ispc support

### ISSUE THREAD

**Issue by semeraro** [ospray/ospray#567]
Hi, 
I am building ospray 2.12.0 on a windows environment.  This version of ospray requires embree 4.0.0 I believe. Configuring ospray with cmake complains that there is no ispc support in embree. The embree changelog says support for ispc was dropped in version 4.0.0. I can rebuild embree with EMBREE_ISPC_SUPPORT=ON but I dont know what the fallout of that will be.  Do you recommend I do that or bypass the embree ispc support check in the ospray configure? 
Thanks,
Dave

**Comment by johguenther** [comment]
Are you using OSPRay's superbuild? By default it fetches Embree binary packages from GitHub, which even in v4.x are compiled with `EMBREE_ISPC_SUPPORT=ON`. If you manually compile Embree then make sure to set `EMBREE_ISPC_SUPPORT=ON` (because it is now indeed `OFF` per default).
Bypassing the check in OSPRay configure will only work when you aim to solely build the GPU version, for CPU rendering we still need the ISPC bindings from Embree.

**Comment by semeraro** [comment]
Thanks for the reply. I am building ospray against a build of openvkl (superbuild). I had been playing with openvkl first. I think going back to start with ospray and throwing the openvkl switch in the superbuild will give me what I need. Thanks again.
