### ISSUE TITLE
Volume Rendering on Windows

### ISSUE THREAD

**Issue by rvlietstra** [ospray/OSPRay#59]
Hi.
It is stated that windows support is experimental.

Is volume rendering working on windows ? Is qt the only reason the volume viewer is excluded from the build ?

My code runs but I get a white background

These are my steps
1. ospInit
2. ospNewCamera, set all properties, ospCommit(camera)
3. ospNewVolume(block_bricked_volume)
4. set volume dimensions
5. set volume voxel type (ushort)
6. ospNewModel
7. ospAddVolume to model
8. ospSetRegion(volume, data, [0,0,0], [128,128,128])
9. ospNewTransferFunction
10. ospSetObject (volume, transferfunction)
11. ospNewRenderer("dvr"), setObject(model), setObject(camera), commit(renderer)
12. commit volume
13. commit world
14. ospNewFrameBuffer
15. ospRenderFrame

Does volume rendering require lights ?
Anything else I can check ? I assume its fine if the camera is inside the volume.

Thanks!

**Comment by rvlietstra** [comment]
Hi.
Anyone know what I could be doing wrong ?

Thanks!

**Comment by rvlietstra** [comment]
I'v now also tried the raycast_volume_renderer.

Do I need to add geometry slices to the model for the volume rendering to work ?

When I add a triangle in addition to my volume then the triangle is rendered correctly with the scivis renderer but its black when I use either dvr or raycast_volume_renderer, the volume still doesn't show up though ...

**Comment by jeffamstutz** [comment]
Hi rvlietstra,

Sorry for the delayed response. Are you constructing data for the transferfunction? If not, a simple example would be to have a look at a small helper class we are using for our sample apps: 

https://github.com/ospray/OSPRay/blob/devel/apps/common/commandline/SceneParser/volume/VolumeSceneParser.cpp

In that file, command line arguments from main get parsed by the class and constructs an ospray model containing the loaded volume as well as an transferfunction info passed (it creates a default one if nothing was provided). To answer your latest question: slices are *not* required for volume rendering.

Also, just FYI, that code uses some C++ wrappers which we will eventually provide with OSPRay installs (not quite ready for official support yet). Thus an ospray::cpp::Volume is a thin wrapper on top of an OSPVolume, where you can call .set(...) instead of ospSet...(). There are more plans for those wrappers to provide some better safety to using the OSPRay API, but hopefully that will help you understand what you are reading in that code. :)

See if a correctly constructed transferfunction helps with both you seeing the volume at all and seeing if the raycast_volume_renderer then works too. The rest of your list of API calls seems OK to me. Regardless, the raycast_volume_renderer only remains for our data-distributed volume support, which will eventually get moved into the scivis renderer, so using the scivis renderer is recommended if you are not using our experimental code.

Cheers,
Jeff

**Comment by jeffamstutz** [comment]
Also, to answer your original question: yes, Qt is the reason we don't build ospVolumeViewer on Windows. There isn't anything about Qt or volume rendering that OSPRay doesn't enable on Windows, we just haven't prioritized fixing our build setup for our sample apps on Windows yet.

**Comment by rvlietstra** [comment]
Hi.
Thanks for the response.
I was able to set the transfer function and sampling rate and get something showing, looks like I'd need to play with my data and the transfer function to make it look as good as your demos, any tips ? :)

I am using the C api via wrapped C#. I might eventually model my wrapper to mimic the C++ api. I'll use the scivis renderer.

I have some other questions which I'll open other issues for.

Thanks!
