### ISSUE TITLE
User geometry: Failed to create OSPGeometry!

### ISSUE THREAD

**Issue by timbiedert** [ospray/OSPRay#83]
I'm trying to implement a custom geometry type. As a simple starting point to verify compilation settings I have cloned the "Spheres" geometry files and refactored everything to "Myspheres".

The project compiles and links fine (including ispc).   However, when trying to instantiate my custom spheres geometry a runtime exception "Failed to create OSPGeometry!" is thrown.

I assume my compiling/linking is wrong? 

See my CMakeLists and main.cpp below:

```
cmake_minimum_required(VERSION 3.3)
project(MySpheres CXX)

set (CMAKE_CXX_STANDARD 14)
set (CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(ospray REQUIRED)
include(${OSPRAY_USE_FILE})

INCLUDE_DIRECTORIES(${OSPRAY_INCLUDE_DIRS})
INCLUDE_DIRECTORIES_ISPC(${OSPRAY_INCLUDE_DIRS})


OSPRAY_CONFIGURE_ISPC_ISA()
OSPRAY_ADD_LIBRARY(Myspheres Myspheres.cpp Myspheres.ispc)

OSPRAY_ADD_EXECUTABLE(app main.cpp)
OSPRAY_EXE_LINK_LIBRARIES(app Myspheres ${OSPRAY_LIBRARIES})
```

```

#include <ospray/ospray.h>
#include <ospray/ospray_cpp/Geometry.h>

int main(int argc, char* argv[])
{
    ospInit(&argc, (const char **) argv);

    ospray::cpp::Geometry spheres("spheres"); // works

    ospray::cpp::Geometry myspheres("myspheres"); // runtime_error: Failed to create OSPGeometry!

    return 0;
}
```

**Comment by johguenther** [comment]
It looks like the implementation of your user geometry resides in a separate, shared library, which is fine and recommended. However, you need to load that library first so that OSPRay can find the new geometry type (just linking the application may only work with static libraries). So, use

    int32_t ospLoadModule(const char *name);

The naming convention for plugins / modules (on Linux) is `libospray_module_<name>.so`, so you also need to adapt the name:

    OSPRAY_ADD_LIBRARY(ospray_module_Myspheres Myspheres.cpp Myspheres.ispc)

**Comment by timbiedert** [comment]
Hey, thanks for the feedback!

In fact, with your modifications a static library is created (libospray_module_Myspheres.a).  
So ospLoadModule fails with the following runtime exception: libospray_module_Myspheres.so: cannot open shared object file: No such file or directory`

However, when I modify the OSPRAY_ADD_LIBRARY line to create a shared library (`OSPRAY_ADD_LIBRARY(ospray_module_Myspheres SHARED Myspheres.cpp Myspheres.ispc)`), linking fails with the following output:
```
[ 20%] Building CXX object CMakeFiles/ospray_module_Myspheres.dir/Myspheres.cpp.o
[ 40%] Linking CXX shared library libospray_module_Myspheres.so
[ 60%] Built target ospray_module_Myspheres
[ 80%] Linking CXX executable app
libospray_module_Myspheres.so: undefined reference to `Geometry_Constructor___un_3C_s_5B_unGeometry_5D__3E_un_3C_unv_3E_un_3C____un_3C_s_5B_unGeometry_5D__3E_un_3C_s_5B_unModel_5D__3E_REFs_5B_vyDifferentialGeometry_5D_REFs_5B__c_vyRay_5D_unI_3E_un_3C_s_5B_unModel_5D__3E_uniun_3C_s_5B_unMaterial_5D__3E_sse2'
collect2: error: ld returned 1 exit status
```

What am I missing?

**Comment by johguenther** [comment]
Your (now shared) lib needs to be linked against OSPRay as well

    OSPRAY_LIBRARY_LINK_LIBRARIES(ospray_module_Myspheres ${OSPRAY_LIBRARIES})

(Alternatively you could use the new, yet another macro

    OSPRAY_CREATE_LIBRARY(ospray_module_Myspheres
      Myspheres.cpp
      Myspheres.ispc
    LINK
      ${OSPRAY_LIBRARIES}
    )

which combines all these steps, also set its `VERSION` and packages/installs the lib.)

**Comment by timbiedert** [comment]
Thanks, I already tried that, but the error remains the same: 

`libospray_module_Myspheres.so.SOVERSION: undefined reference to Geometry_Constructor___un_3C_s_5B_unGeometry_5D__3E_un_3C_unv_3E_un_3C____un_3C_s_5B_unGeometry_5D__3E_un_3C_s_5B_unModel_5D__3E_REFs_5B_vyDifferentialGeometry_5D_REFs_5B__c_vyRay_5D_unI_3E_un_3C_s_5B_unModel_5D__3E_uniun_3C_s_5B_unMaterial_5D__3E_sse2`

My CMake file:
```
cmake_minimum_required(VERSION 3.3)
project(MySpheres CXX)

set (CMAKE_CXX_STANDARD 14)
set (CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(ospray REQUIRED)
include(${OSPRAY_USE_FILE})

INCLUDE_DIRECTORIES(${OSPRAY_INCLUDE_DIRS})
INCLUDE_DIRECTORIES_ISPC(${OSPRAY_INCLUDE_DIRS})


OSPRAY_CONFIGURE_ISPC_ISA()
#OSPRAY_ADD_LIBRARY(ospray_module_Myspheres SHARED Myspheres.cpp Myspheres.ispc)
#OSPRAY_LIBRARY_LINK_LIBRARIES(ospray_module_Myspheres ${OSPRAY_LIBRARIES})
OSPRAY_CREATE_LIBRARY(ospray_module_Myspheres Myspheres.cpp Myspheres.ispc LINK ${OSPRAY_LIBRARIES} )

OSPRAY_ADD_EXECUTABLE(app main.cpp)
OSPRAY_EXE_LINK_LIBRARIES(app ospray_module_Myspheres ${OSPRAY_LIBRARIES})

```

**Comment by johguenther** [comment]
OK, this is a bug in the ISA configuration. Until we have a proper fix please include this workaround before calling `OSPRAY_CONFIGURE_ISPC_ISA()`:
```cmake
    SET(EMBREE_ISA_SUPPORTS_AVX    FALSE)
    SET(EMBREE_ISA_SUPPORTS_AVX2   FALSE)
    SET(EMBREE_ISA_SUPPORTS_AVX512 FALSE)
  
    # Workaround - name changed from EMBREE_ISA to EMBREE_MAX_ISA in 2.10 -> 2.11
    IF (DEFINED EMBREE_ISA)
      SET(EMBREE_ISA_NAME EMBREE_ISA)
    ELSE ()
      SET(EMBREE_ISA_NAME EMBREE_MAX_ISA)
    ENDIF()
  
    IF (${${EMBREE_ISA_NAME}} STREQUAL "AVX")
      SET(EMBREE_ISA_SUPPORTS_AVX TRUE)
    ELSEIF (${${EMBREE_ISA_NAME}} STREQUAL "AVX2")
      SET(EMBREE_ISA_SUPPORTS_AVX  TRUE)
      SET(EMBREE_ISA_SUPPORTS_AVX2 TRUE)
    ELSEIF (${${EMBREE_ISA_NAME}} STREQUAL "AVX512KNL")
      SET(EMBREE_ISA_SUPPORTS_AVX    TRUE)
      SET(EMBREE_ISA_SUPPORTS_AVX2   TRUE)
      SET(EMBREE_ISA_SUPPORTS_AVX512 TRUE)
    ENDIF()
````
Additionally, to successfully load your lib you need to include a plugin register function, something like
```c
    extern "C" void ospray_init_module_Myspheres()
    {
        std::cout << "loading 'Myspheres' module" << std::endl;
    }
````

**Comment by tbiedert** [comment]
Hi,

I was just trying to resurrect some old user geometry code, which used to work in OSPRay 1.2.0.

However, now in OSPRay 1.3.1 I get the _Failed to create OSPGeometry!_ exception again.

The CMake part that used to work:
```
OSPRAY_CREATE_LIBRARY(ospray_module_ParticleSurface ParticleSurface.cpp ParticleSurface.ispc LINK ${OSPRAY_LIBRARIES})

OSPRAY_ADD_EXECUTABLE(fpmvis main.cpp)
OSPRAY_EXE_LINK_LIBRARIES(fpmvis ospray_module_ParticleSurface ${OSPRAY_LIBRARIES})
```

The last two commands OSPRAY_ADD_EXECUTABLE/OSPRAY_EXE_LINK_LIBRARIES are not available anymore. Replacing them with standard ADD_EXECUTABLE/TARGET_LINK_LIBRARIES allows to compile, but the module can not be loaded at runtime.

What's the current way to go for loading user modules?

Thanks!

**Comment by Twinklebear** [comment]
You'll want to use `OSPRAY_CREATE_LIBRARY` for modules and `OSPRAY_CREATE_APPLICATION` for applications now, check out the [pluggable geometry example](https://github.com/ospray/ospray/tree/master/modules/pluggableGeometryExample) for an example module.

**Comment by tbiedert** [comment]
Hi, thanks! Yes, I've seen the pluggable geometry example in the mean time and updated my post above. However, I can not spot the difference / what's missing. Do you see the problem?

**Comment by jeffamstutz** [comment]
One thing to look out for is if you accidently have an old version of the module on your ```$LD_LIBRARY_PATH``` (which often is an OSPRay install from some time in the past). On Linux we use ```dlopen()``` to open shared libraries, which will look on ```LD_LIBRARY_PATH``` first (as expected).

We have on our TODO list to add version checks to ```ospLoadModule()``` to make sure that the module loaded was built with the same version of OSPRay. The upcoming ```v1.4.0``` release has so much in it that we won't have that implemented by then (mid September), but have it on the short list for ```v1.5.0```!

FWIW, the stuff you posted earlier looks OK to me. If it's not a ```LD_LIBRARY_PATH``` problem, we'll need to dig deeper.

**Comment by tbiedert** [comment]
Thanks Jeff! I don't see or think there are any library conflicts.

Checking the loadLocalModule() code, the library is probably loaded fine. I receive OSP_UNKNOWN_ERROR, which is only returned if the initMethod (ospray_init_module_particleSurface in my case) throws an exception.

My init method in ParticleSurface.cpp is:
```
extern "C" void ospray_init_module_particleSurface()
{
    std::cout << "Loading 'Particle Surface' module" << std::endl;
}
```

**Comment by jeffamstutz** [comment]
Hmmmm, that is very strange. Can you confirm that ```getSymbol()``` succeeds?

We turn any ```std::runtime_error``` into an ```OSP_UNKNOWN_ERROR```, but if you don't have an OSPRay error function installed on the device (done manually), then you may not be getting the error messages correctly. If an exception is thrown in any API function, then we catch it and keep going for C99's sake, which is confusing here because there is a path inside ```loadLocalModule()``` that can return ```OSP_UNKNOWN_ERROR``` in addition to getting that as a return value from a generic thrown exception.

Somewhat tangent to this issue, I've noticed its possible to install a status message callback through environment variables and/or command line options, but not an error status message....that's a bug! Looks like there's some need to make the default experience a bit better...

**Comment by tbiedert** [comment]
Wow, thanks. The error callback made things clear:  _OSPRay error: 1 - could not open module lib ospray_module_particleSurface due to libospray_module_particleSurface.so: cannot open shared object file: No such file or directory_

But that file does exist in the build folder.

Wow, it works if I start my app with `LD_LIBRARY_PATH=. ./fpmvis`

**Comment by jeffamstutz** [comment]
Bugs, ugh. Something may have changed wrt the paths considered and/or RPATH perhaps getting involved...(?)

Regardless, we'll try to clean up this experience ```v1.4.0```. There shouldn't be any fundamental difference with modules betwee ```v1.2.0``` and ```v1.3.1```, sorry about the confusion! Thanks for being persistent. :)

**Comment by tbiedert** [comment]
I'm not sure OSPRay is to blame here. Maybe there is something fishy about my build system. Anyway, thanks for your help!

**Comment by johguenther** [comment]
I just noticed that we still claim in the documentation, that the application directory is also searched for modules. That has been the case in the past, but not anymore (since v1.2.0). `RPATH` is considered, thus, if `libospray.so` is found, then module particleSurface should be found as well (assuming it is in the same folder).

**Comment by tbiedert** [comment]
This seems to be a never-ending story for me...

So everything works fine on my desktop machine, however the user geometry fails to be initialized on my university's cluster.

If I run with `LD_DEBUG=libs` on my desktop, I get this:
```
     18671:     find library=libospray_module_ParticleSurface.so [0]; searching
     18671:      search path=./tls/x86_64:./tls:./x86_64:.              (LD_LIBRARY_PATH)
     18671:       trying file=./tls/x86_64/libospray_module_ParticleSurface.so
     18671:       trying file=./tls/libospray_module_ParticleSurface.so
     18671:       trying file=./x86_64/libospray_module_ParticleSurface.so
     18671:       trying file=./libospray_module_ParticleSurface.so
     18671:
     18671:
     18671:     calling init: ./libospray_module_ParticleSurface.so
     18671:
Loading 'Particle Surface' module  // this is printed in the ospray_init_module_ParticleSurface() function.
```

However, on the cluster I get this output:
```
     68981:     find library=libospray_module_ParticleSurface.so [0]; searching
     68981:      search path=/home/tbiedert/local/lib64:/home/tbiedert/local/lib64/../lib/tls/x86_64:/home/tbiedert/local/lib64/../lib/tls:/home/tbiedert/local/lib64/../lib/x86_64:/home/tbiedert/local/lib64/../lib                (RPATH from file ./fpmvis)
     68981:       trying file=/home/tbiedert/local/lib64/libospray_module_ParticleSurface.so
     68981:       trying file=/home/tbiedert/local/lib64/../lib/tls/x86_64/libospray_module_ParticleSurface.so
     68981:       trying file=/home/tbiedert/local/lib64/../lib/tls/libospray_module_ParticleSurface.so
     68981:       trying file=/home/tbiedert/local/lib64/../lib/x86_64/libospray_module_ParticleSurface.so
     68981:       trying file=/home/tbiedert/local/lib64/../lib/libospray_module_ParticleSurface.so
     68981:      search path=/home/tbiedert/local/lib64:/home/tbiedert/local/lib:tls/x86_64:tls:x86_64:         (RPATH from file ./fpmvis)
     68981:       trying file=/home/tbiedert/local/lib64/libospray_module_ParticleSurface.so
     68981:       trying file=/home/tbiedert/local/lib/libospray_module_ParticleSurface.so
     68981:       trying file=tls/x86_64/libospray_module_ParticleSurface.so
     68981:       trying file=tls/libospray_module_ParticleSurface.so
     68981:       trying file=x86_64/libospray_module_ParticleSurface.so
     68981:       trying file=libospray_module_ParticleSurface.so
     68981:
     68981:     libospray_module_ParticleSurface.so: error: symbol lookup error: undefined symbol: _ZN6ospray13postStatusMsgERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj (fatal)

     68981:     /home/tbiedert/local/lib64/libospray_common.so.0: error: symbol lookup error: undefined symbol: ospray_create_geometry__particleSurface (fatal)
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to create OSPGeometry!
```

So it seems like the module can not be loaded due to `libospray_module_ParticleSurface.so: error: symbol lookup error: undefined symbol: _ZN6ospray13postStatusMsgERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj (fatal)` ...

Have you guys ever seen something like this? Any ideas?

Both machines use OSPRay 1.4.1.  Compiler is different, though: GCC 6.3 on desktop, 7.1 on cluster.

Thanks!

**Comment by johguenther** [comment]
`postStatusMsg` is defined in `libospray.so`; can you please check with `nm` that the name mangling of that function in `libospray.so` (with `T`) and `libospray_module_ParticleSurface.so` (with `U`) is the same? Because with C++ it indeed can happen that compilation with different compilers cause linking errors. The recommendation is to compile all modules with the same compiler (thus you may need to recompile OSPRay on the cluster).

**Comment by tbiedert** [comment]
Thanks Johannes, you were right! There was indeed a compiler mismatch between the OSPRay library and my client app.
