### ISSUE TITLE
Multiple intersecting volumes; clipping geometry

### ISSUE THREAD

**Issue by tbiedert** [ospray/ospray#84]
Currently, it's not possible to render multiple volumes which are intersecting/overlapping. 

Is this planned for the future?

**Comment by ingowald** [comment]
The topic does indeed come up now and then .... however, the problem is 
that it isn't even clearly defined what exactly "overlapping" volumes 
mean. For example, for any point X that is in two different volumes, do 
we average the scalar values? Add them? blend them somehow? Or take the 
minmum/maximum? Once we have this scalar value, which transfer functoin 
do we use?

Or do we first evluate each volume's transfer function and then 
add/mul/blend/min/max the respective opacities?

Interestingly, though many different users/customers have asked about 
this feature, there seems to be little consensus as to what we should 
actually implement :-/. Of course, one option would be to implement all 
those options in some generic way - possibly using some kind of flags to 
indicate which operation to apply - but without actual use cases this is 
a recipe for desaster.

Until we get a better idea of what users would actually require, the 
current plan is to allow multiple volumes, but to simply ignore whether 
or not they overlap; i.e., to treat them just as if they were behind 
each other. That's not perfect, but easy to do, and will likely do the 
trick for most users, anyway.

Can you be a bit more specific as to for what you'd actually need 
overlapping volumes, and what exactly you'd expect them to do?

Cheers,

Ingo

**Comment by florianlink** [comment]
I think typically you want to classify each sample and blend them together,
at least that is how we do it in our GPU Volume Renderer / GLSL shader.
But it is easier to customize with shaders, because our users can write
their own shader
function to combine volumes, which you can't do in OSPray.

By the way, having a Tag Volume and a Mask Volume would also be great.
The Tag Volume would give an index into a 2D LUT and the Mask Volume could
be used to
mask parts of the volume.

**Comment by jeffamstutz** [comment]
FWIW, you can always write a renderer that does exactly what you want. You can do this via the OSPRay SDK (found in the include/ directory of an OSPRay install), or by writing an "OSPRay module". I'll include what I just posed in issue #49 here:

An example of a simple OSPRay module can be found here: https://github.com/jeffamstutz/module_nanort

The example implements a triangle mesh which forwards ray intersection calls to a small, header-only ray tracing library called NanoRT. While the geometry type _itself_ is not related to this topic, it is a fairly small example of how to extend OSPRay in the source tree and use it in the sample viewer. Any object type (including renderers, which are really just monolithic primary-ray shaders) which doesn't meet your needs, you can substitute your own instead.

**Comment by timbiedert** [comment]
Similar to @florianlink, we also need to classify each sample separately and then blend the color values. We're also doing this currently in our OpenGL shader.

Regarding masking:  This is also a critical feature we need. However, I think a **masking geometry** would be even more appropriate and powerful. I imagine this would also be rather simple to implement by keeping track of the number of remaining intersections with the masking geometry along the sample ray  (odd: inside volume -> sample;  even: outside -> don't sample).

Thanks for your hint on writing a custom renderer. However, if avoidable, we would rather not want to maintain a modified SciVis renderer fork.

**Comment by johguenther** [comment]
Re masking geometry: is complex geometry needed or do we speak of (several) cut/clip planes?

**Comment by timbiedert** [comment]
Complex / non-convex geometry, including holes.  That's why I thought using a general geometry object would be very powerful and suitable, as it already provides means to retrieve all intersections.   Keeping track of the remaining intersections while sampling shouldn't be too much overhead, I guess.

Thanks for considering this!

**Comment by johguenther** [comment]
Okay :-) Some more questions then:
- One global mask geometry? Or different mask geometries per volume (assuming multiple active volumes)? Note that this also needs to be managed by the application.
- How is "inside" and "outside" defined (i.e. which part is masking). Could we agree on using the normals (either provided per vertex, or determined by the geometry, e.g. winding order)? Like: normals pointing to the outside, and the outside is culled.

**Comment by timbiedert** [comment]
I imagined a separate mask geometry per volume, like ospSet(volume, "mask", geometry).  Would this be more difficult to implement than a single shared geometry?

Regarding inside/outside:  Assuming a **closed** geometry, I would prefer something like the even-odd-rule, independent of normals.  As I sketched before, in a first pass one could record all intersections with the geometry along the ray and sort them.  Then, at every sample location, check if we "passed" an intersection and pop it from the queue. The sample is inside the mask, it the number of remaining intersections is odd.

**Comment by johguenther** [comment]
Hmm, even-odd has some problems:
- when the camera is inside the geometry (although alleviated when looking at the number of remaining intersections)
- for example when we have a sphere as mask geometry we always end up with a spherical volume, but cannot use the sphere to cut a hole in the volume (which we could by just flipping the normals)

**Comment by timbiedert** [comment]
Okay! :-)  I would also be happy with the normals-based approach; just thought the even-odd thing might be easy to implement.

Thank you for your feedback!  Looking forward to it :-)

**Comment by jeffamstutz** [comment]
We will most likely address this issue specifically when we reach OSPRay 2.0 (targeting later this year). Part of OSPRay 2.0 will be moving on from ispc and just use C++ for shading. That will open up some possibilities with making it easier to extend certain parts of the API (e.g. think "a volume sampler"). Furthermore, programmable callbacks (which the calling application could specify) would be a much more tractable problem to solve without the C++/ispc barrier.

Until then, it's not possible for us to satisfy all of the multitudes of methods to blend multiple volume samples: when we talk to users, everyone wants something different specific to their application. Right now, your best bet is to implement your own renderer which handles multiple volumes the way your applications wants.

**Comment by m-urschel** [comment]
Too bad... But thanks for answering :)

**Comment by straaljager** [comment]
Hi, are the clipping planes still on track for the OSPRay 2.0 release?

**Comment by jeffamstutz** [comment]
Technically yes (?), though OSPRay development efforts are concentrated on demo prep for ISC (going on right now) and SIGGRAPH right now. When we get back to OSPRay 2.0 efforts, we will certainly look at clipping planes/geometry features described here....LOTS and LOTS to do. :)

**Comment by straaljager** [comment]
Hi Jeff, is there an update on OSPRay v2.0? I remember someone from the dev team mentioning a release before ISC. Is that still the case?

**Comment by miroslawpawlowski** [comment]
For all waiting, a note that work on clipping geometries has started and there are some first results. 

Below is a cube made of spheres clipped from the top with four bigger spheres. Rendered with scivis, shadows and AO enabled.
![screenshot4](https://user-images.githubusercontent.com/45656675/56804019-9d60f800-6824-11e9-81b0-2c1366a01673.png)

Clipping works with volumes as well. Please see similar cube and unstructured volume clipped with a single sphere. 
![screenshot3](https://user-images.githubusercontent.com/45656675/56803784-ea909a00-6823-11e9-9df4-83d916077da9.png)

**Comment by straaljager** [comment]
Nice! Good to see that lighting remains unaffected by the clipping geometry (meaning light rays are not clipped).

**Comment by jeffamstutz** [comment]
We support overlapping volumes in both `scivis` and `pathtracer` in `v2.0`. Clipping geometries are covered in another issue, so this can be closed.
